# Generated by Django 4.0.1 on 2022-02-08 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adrianshop', '0002_basket_product_order_basketitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_tag',
            field=models.CharField(choices=[('Hat', 'Hat'), ('Shirt', 'Shirt'), ('T-shirt', 'Tshirt'), ('Hoodie', 'Hoodie'), ('Trouser', 'Trouser'), ('Miscellaneous', 'Misc')], default='Miscellaneous', max_length=13),
        ),
    ]
