# Generated by Django 4.0.1 on 2022-02-08 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adrianshop', '0004_rename_basketitems_basketitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basket',
            old_name='id_active',
            new_name='is_active',
        ),
    ]
