# Generated by Django 4.0.1 on 2022-02-08 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adrianshop', '0005_rename_id_active_basket_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.TextField(default=''),
        ),
    ]
