# Generated by Django 4.0.1 on 2022-02-08 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adrianshop', '0006_order_shipping_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_tag',
            field=models.CharField(choices=[('Hats', 'Hat'), ('Shirts', 'Shirt'), ('T-shirts', 'Tshirt'), ('Hoodies', 'Hoodie'), ('Trousers', 'Trouser'), ('Miscellaneous', 'Misc')], default='Miscellaneous', max_length=13),
        ),
    ]
