# Generated by Django 4.0.1 on 2022-02-09 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adrianshop', '0008_alter_product_product_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_tag',
            field=models.CharField(choices=[('Hats', 'Hat'), ('Shirts', 'Shirt'), ('Hoodies', 'Hoodie'), ('Trousers', 'Trouser'), ('Miscellaneous', 'Misc')], default='Miscellaneous', max_length=13),
        ),
    ]
