#!/usr/bin/env python3

a = int(input())
b = int(input())
c = int(input())
d = int(input())
e = int(input())
f = int(input())
g = int(input())
h = int(input())
i = int(input())
j = int(input())

a = (a * (a % 2))
b = (b * (b % 2))
c = (c * (c % 2))
d = (d * (d % 2))
e = (e * (e % 2))
f = (f * (f % 2))
g = (g * (g % 2))
h = (h * (h % 2))
i = (i * (i % 2))
j = (j * (j % 2))

print(a + b + c + d + e + f + g + h + i + j)
